version: "3.9"

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pokus
      POSTGRES_DB: postgresql
    ports:
      - "5432:5432"